title: Abhijit Zala # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: A look at some of my projects
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # Google Analytics tracking ID 

