title: Example Title # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: A look at things I have made
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # Google Analytics tracking ID 

